version: "3.8"

services:

  app:
    build: .
    working_dir: $APP_DEST
    environment:
      APP_ENV: local
      APP_URL: http://localhost:$APP_PORT
      DB_HOST: db
      DB_PORT: $DB_PORT
      DB_DATABASE: $DB_NAME
      DB_USERNAME: $DB_USER
      DB_PASSWORD: $DB_PASS
    volumes:
      - $APP_SRC:$APP_DEST
      - ./xdebug/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/php.ini-development:/usr/local/etc/php/php.ini
      - php:/usr/local/etc/php
    depends_on:
      - db
      - cache
      - horizon
      - websockets
      - scheduler

  horizon:
    build: .
    working_dir: /var/www/starter/
    command: php artisan horizon
    restart: on-failure
    volumes:
      - $APP_SRC:$APP_DEST
    depends_on:
      - cache

  websockets:
    build: .
    working_dir: /var/www/starter/
    command: php artisan websockets:serve
    ports:
      - "6001:6001"
    restart: on-failure
    volumes:
      - $APP_SRC:$APP_DEST
    depends_on:
      - cache

  scheduler:
    build: .
    working_dir: /var/www/starter/
    command: php artisan schedule:work
    restart: on-failure
    volumes:
      - $APP_SRC:$APP_DEST
    depends_on:
      - cache

  web:
    image: nginx
    ports:
      - "$APP_PORT:80"
    volumes:
      - $APP_SRC:$APP_DEST
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  cache:
    image: redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASS}
    ports:
      - "6380:6379"
    environment:
      REDIS_PASS: $REDIS_PASS
    volumes:
      - cache:/data

  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
    expose:
      - "3306"
    volumes:
      - database:/var/lib/mysql
  #      - ./database/config.d/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  adminer:
    image: adminer
    ports:
      - "$ADMINER_PORT:8080"
    depends_on:
      - db

volumes:
  data:
  cache:
  php:
  database:
